### ISSUE TITLE
MoneyMismatchException:contextMismatch when using different context

### ISSUE THREAD

**Issue by BertKooij** [whitecube/php-prices#4]
When using this library with a Money instance with a custom context calculating the inclusive/exclusive price will throw an exception. 

> The monies do not share the same context. If this is intended, use plus($money->toRational()) instead of plus($money).

In my use case the context should not round the numbers which could be achieved with a custom context. The default context auto rounds the values to the default rounding of the used currency.

**Comment by toonvandenbos** [comment]
Thanks for your PR. Released under version [2.0.1](https://github.com/whitecube/php-prices/releases/tag/v2.0.1).
